language: php

php:
  - 5.6
  - 7.0
  - 7.1

script: phpunit  --coverage-clover build/logs/clover.xml

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install




